[package]
name = "b2048-game"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.13"
rand = "0.8.5"
itertools = "0.12.1"
serde = { version = "1.0.197", features = ["derive"] }
log = "0.4.21"
